const express=require('express')
const {connectDb}=require('./config/db')
const userRoute=require('./routes/userRoute')
const adminRoute=require('./routes/adminRoute')
const {errorHandler}=require('./middlewares/errorHandler')
connectDb()
const app=express()
const port=process.env.PORT || 5000

app.use(express.json())
app.use(express.urlencoded({extended:true}))
app.use('/api/',userRoute)
app.use('/api/admin',adminRoute)
app.use(errorHandler)
app.listen(port,()=>console.log(`server Started at ${port}`))
